---
debug: false
only_extant_files: False
downloaded: downloaded.json
validate: true
schema: https://schema.catalog.sd2e.org/schemas/sample_set.json

logs:
  level: INFO
  token: ~

catalogstore:
  debug: false
  uuid5_namespace: sd2e.org
  storage_system: data-sd2e-community
  base: /work/projects/SD2E-Community/prod/data
  store: uploads/
  root: uploads/
  batch: 1000
  collections:

storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data

mongodb:
  port: 27020
  database: catalog
  host: catalog.sd2e.org
  username: catalog
  password: ~

pipelines:
  active: False
  job_manager_id: G56vjoAVzGkkq
