---
debug: false
only_extant_files: False
downloaded: downloaded.json
validate: true
schema: https://schema.catalog.sd2e.org/schemas/sample_set.json

logs:
  level: DEBUG
  token: ~

catalogstore:
  debug: false
  uuid5_namespace: sd2e.org
  storage_system: data-sd2e-community
  base: /work/projects/SD2E-Community/prod/data
  store: uploads/
  root: uploads/
  batch: 1000
  collections:

storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
  data-sd2e-projects.sd2e-project-21:
    posix_path: /work/projects/SD2E-Community/prod/projects/sd2e-project-21
  data-projects-safegenes:
    posix_path: /work/projects/DARPA-SD2-Partners/safegenes

mongodb:
  port: 27020
  database: catalog_staging
  host: catalog.sd2e.org
  username: catalog
  password: ~

pipelines:
  active: False
  pipeline_manager_id: pipelines-manager.prod
  pipeline_manager_nonce: ~
  job_manager_id: jobs-manager.prod
  job_manager_nonce: SD2E_z00EbBOeoYJry
  job_indexer_id: jobs-indexer.prod
  job_indexer_nonce: SD2E_RyZRVDMgXK1DV
